a, b, c = int(input()), int(input()), int(input())
a1, b1, c1 = int(input()), int(input()), int(input())
x1 = (a // a1) * (b // b1) * (c // c1)
x2 = (a // a1) * (b // c1) * (c // b1)
x3 = (a // b1) * (b // a1) * (c // c1)
x4 = (a // b1) * (b // c1) * (c // a1)
x5 = (a // c1) * (b // b1) * (c // a1)
x6 = (a // c1) * (b // a1) * (c // b1)
print(max(x1, x2, x3, x4, x5, x6))
